### ISSUE TITLE
Subscriptions over MQTT is not supported.

### ISSUE THREAD

**Issue by BrendaGM** [aws-samples/aws-amplify-appsync-graphql-real-time-canvas#28]
Following the instructions in the readme, the response is an error.

{
  "errors" : [ {
    "errorType" : "BadRequestException",
    "message" : "Subscriptions over MQTT is not supported."
  } ]
}

Region: us-east-1

Any idea?

**Comment by kamitath** [comment]
It seems aws-amplify module is used in this application is too old one.
You should update aws-amplify version in package.json after that this app works fine.
